transcode:
  # hwaccel: videotoolbox
  rules:
    -
      from: 
        track: h264
        codec: h264
      to: 
        - 
          track: h265
          codec: hevc
          args:
            preset: ultrafast
            tune: zerolatency