#key = md5(密钥+流名称)
#iv = md5(流名称）前一半
global:
  loglevel: info # 日志级别，可选值：debug,info,warn,error,panic,fatal
  http:
    listenaddr: :8080 # api端口

rtmp:
  tcp:
    listenaddr: :1935 # rtmp监听端口
  chunksize: 65535

# rtmp://23.237.196.99/live/test
# aliyunlive.droolx.cn
cdn:
  host: pushalkjhdfasdf.shnhyl.com.cn  # cdn域名
  pushkey: 1XjZreXdEtJYg6hr # cdn 加密key
  expiretime: 3600
  fromtrack: "h264_enc"

crypto: # 加密设置
  filter: .*  # 流过滤
  fromtrack: .* # track 过滤
  key:
    key: sfafxxsfsdf  # 加密key
    
    